/**:
  ros__parameters:
    moveit_controller_manager:
        moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - iiwa_arm_controller

      iiwa_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - joint_a1
          - joint_a2
          - joint_a3
          - joint_a4
          - joint_a5
          - joint_a6
          - joint_a7
