/**:
  ros__parameters:
    default_planning_pipeline: pilz
    planning_pipelines: [pilz, ompl]
    pilz:
      planning_plugin: pilz_industrial_motion_planner/CommandPlanner
      request_adapters: ""
      start_state_max_bounds_error: 0.1
    ompl:
      planning_plugin: ompl_interface/OMPLPlanner
      request_adapters:
          default_planner_request_adapters/AddTimeOptimalParameterization
          default_planner_request_adapters/FixWorkspaceBounds
          default_planner_request_adapters/FixStartStateBounds
          default_planner_request_adapters/FixStartStateCollision
          default_planner_request_adapters/FixStartStatePathConstraints
      start_state_max_bounds_error: 0.1
