name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          mkdir -p ${{github.workspace}}/src
      - uses: actions/checkout@v2
        with:
          path: src/iiwa_ros2

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: ros:humble
          options: -v ${{github.workspace}}/:/ros/
          run: |
            cd /ros
            apt update && apt upgrade
            . /opt/ros/humble/setup.sh
            vcs import < src/iiwa_ros2/iiwa_ros2.repos
            rosdep install --ignore-src --from-paths . -y -r
            colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: ros:humble
          options: -v ${{github.workspace}}/:/ros/
          run: |
            cd /ros
            apt update && apt upgrade
            . /opt/ros/humble/setup.sh
            vcs import < src/iiwa_ros2/iiwa_ros2.repos
            rosdep install --ignore-src --from-paths . -y -r
            colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
            colcon test --packages-skip gazebo_ros2_control
            colcon test-result
